### ISSUE TITLE
Doesn't work with morph relation

### ISSUE THREAD

**Issue by SpinyMan** [johnnyfreeman/laravel-custom-relation#5]
`if (isset($dictionary[$key = $model->getKey()])) {`

Compare works only with the fields that exists in a model. By the way morph `match` does like this:

`if (isset($dictionary[$key = $model->getAttribute($this->localKey)])) {`

Could u add possibility to define keys?

**Comment by SpinyMan** [comment]
Anybody home?

**Comment by johnnyfreeman** [comment]
Not sure what you are asking for. Could you provide an example of what you are wanting to do?

**Comment by SpinyMan** [comment]
Oops... I'm talking about 36864/laravel-custom-relation fork... he added preliminary eager loading support but it doesn't work with morph relation because it uses different column names. Example:
`$child->parent_id = $parent->id` // this is normal behaviour
`$child->tagable_id && $child->tagable_type = $tag->id` // morph
So his function `buildDictionary` uses only first example...

```
protected function buildDictionary(Collection $results, $models)
{
	// First we will build a dictionary of child models keyed by the foreign key
	// of the relation so that we will easily and quickly match them to their
	// parents without having a possibly slow inner loops for every models.
	$dictionary = [];
	foreach($models as $model){
		$dictionary[$model->getKey()] = $results->where($model->getKeyName(), $model->getKey())->toArray();
	}
	return $dictionary;
}
```
Here `$model->getKeyName()` returns $parent->id but I need tagable_id...

**Comment by johnnyfreeman** [comment]
Oh I see... That fork hasn't been merged in yet. Although there is an open thread for it. Would you mind posting your question in the original thread for that?  Here's a link: #4 

Thanks man!
